/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pedram Ashoori (https://sketchfab.com/pedramashoori)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sci-fi-level-design-aebbcf6e4f1641f2a77c668c4abbe723
title: (Sci fi) Level design
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Level(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/level/scene.gltf', '/models/level/scene.bin')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[-666.6, -553.25, -167961]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <group position={[198.5, -1069.82, 1.44]} rotation={[Math.PI / 2, 0, 0]} scale={[0.33, 0.34, 0.14]}>
                <group position={[0, 0, -15.25]}>
                  <mesh
                    geometry={nodes['Box006_03_-_Default_0'].geometry}
                    material={nodes['Box006_03_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[71.04, -1069.82, 1.44]} rotation={[Math.PI / 2, 0, 0]} scale={[0.33, 0.34, 0.14]}>
                <group position={[0, 0, -15.25]}>
                  <mesh
                    geometry={nodes['Box007_Material_#29_0'].geometry}
                    material={nodes['Box007_Material_#29_0'].material}
                  />
                </group>
              </group>
              <group
                position={[161.67, -1005.46, 1.4]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={[-0.24, 0.24, 0.24]}>
                <mesh
                  geometry={nodes['Star004_Material_#26_0'].geometry}
                  material={nodes['Star004_Material_#26_0'].material}
                />
              </group>
              <group position={[161.15, -1134.39, 1.4]} rotation={[Math.PI / 2, 0, 0]} scale={[0.24, 0.24, 0.24]}>
                <mesh
                  geometry={nodes['Star003_Material_#26_0'].geometry}
                  material={nodes['Star003_Material_#26_0'].material}
                />
              </group>
              <group position={[-266.76, 127.16, 85.47]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line013_01_-_Default_0'].geometry}
                    material={nodes['Line013_01_-_Default_0'].material}
                  />
                  <mesh
                    geometry={nodes['Line013_01_-_Default_0_1'].geometry}
                    material={nodes['Line013_01_-_Default_0_1'].material}
                  />
                </group>
              </group>
              <group position={[353.09, -1886.13, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line019_01_-_Default_0'].geometry}
                    material={nodes['Line019_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[353.09, -1727.53, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line021_01_-_Default_0'].geometry}
                    material={nodes['Line021_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-75.22, -1885.84, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line023_01_-_Default_0'].geometry}
                    material={nodes['Line023_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-75.22, -1727.24, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line024_01_-_Default_0'].geometry}
                    material={nodes['Line024_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[153.97, -1370.4, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line027_01_-_Default_0'].geometry}
                    material={nodes['Line027_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[153.97, -1211.8, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line028_01_-_Default_0'].geometry}
                    material={nodes['Line028_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-58.32, -1966.08, -0.36]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-0.43, 0.43, 0.43]}>
                <mesh
                  geometry={nodes['Bwalle_002_Material_#33_0'].geometry}
                  material={nodes['Bwalle_002_Material_#33_0'].material}
                />
              </group>
              <group
                position={[336.32, -1966.08, -0.36]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-0.43, 0.43, 0.43]}>
                <mesh
                  geometry={nodes['Bwalle_003_Material_#33_0'].geometry}
                  material={nodes['Bwalle_003_Material_#33_0'].material}
                />
              </group>
              <group position={[137.73, -851.8, -5.05]} rotation={[0, 0, -Math.PI / 2]} scale={[0.97, 0.99, 1.22]}>
                <mesh geometry={nodes.Box014_dfhg_0.geometry} material={nodes.Box014_dfhg_0.material} />
              </group>
              <group position={[138.75, -991.54, -7.41]} rotation={[Math.PI / 2, 0, -Math.PI / 4]}>
                <mesh geometry={nodes.Tube001_adaptor_0.geometry} material={nodes.Tube001_adaptor_0.material} />
              </group>
              <group position={[137.26, -583.04, -5.35]} rotation={[0, 0, -Math.PI / 2]} scale={[0.97, 0.99, 1.22]}>
                <mesh geometry={nodes.Box015_dfhg_0.geometry} material={nodes.Box015_dfhg_0.material} />
              </group>
              <group position={[-324.11, -421.28, -5.31]} rotation={[0, 0, Math.PI / 2]} scale={[0.97, 0.99, 1.22]}>
                <mesh geometry={nodes.Box016_dfhg_0.geometry} material={nodes.Box016_dfhg_0.material} />
              </group>
              <group position={[-324.11, 349.61, -5.31]} rotation={[0, 0, Math.PI / 2]} scale={[-0.97, 0.99, 1.22]}>
                <mesh geometry={nodes.Box017_dfhg_0.geometry} material={nodes.Box017_dfhg_0.material} />
              </group>
              <group position={[137.26, 511.38, -5.35]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.97, 0.99, 1.22]}>
                <mesh geometry={nodes.Box018_dfhg_0.geometry} material={nodes.Box018_dfhg_0.material} />
              </group>
              <group
                position={[198.5, 998.15, 1.44]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-0.33, 0.34, 0.14]}>
                <group position={[0, 0, -15.25]}>
                  <mesh
                    geometry={nodes['Box019_03_-_Default_0'].geometry}
                    material={nodes['Box019_03_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[71.04, 998.15, 1.44]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-0.33, 0.34, 0.14]}>
                <group position={[0, 0, -15.25]}>
                  <mesh
                    geometry={nodes['Box020_Material_#29_0'].geometry}
                    material={nodes['Box020_Material_#29_0'].material}
                  />
                </group>
              </group>
              <group position={[161.67, 933.8, 1.4]} rotation={[Math.PI / 2, 0, 0]} scale={[0.24, 0.24, 0.24]}>
                <mesh
                  geometry={nodes['Star005_Material_#26_0'].geometry}
                  material={nodes['Star005_Material_#26_0'].material}
                />
              </group>
              <group
                position={[161.15, 1062.72, 1.4]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-0.24, 0.24, 0.24]}>
                <mesh
                  geometry={nodes['Star006_Material_#26_0'].geometry}
                  material={nodes['Star006_Material_#26_0'].material}
                />
              </group>
              <group position={[353.09, 1655.86, 52.56]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line029_01_-_Default_0'].geometry}
                    material={nodes['Line029_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-75.22, 1655.58, 52.56]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line031_01_-_Default_0'].geometry}
                    material={nodes['Line031_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[153.97, 1298.73, 52.56]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line034_01_-_Default_0'].geometry}
                    material={nodes['Line034_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[153.97, 1140.14, 52.56]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line035_01_-_Default_0'].geometry}
                    material={nodes['Line035_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[138.75, 919.87, -7.41]} rotation={[-Math.PI / 2, 0, -2.36]} scale={[-1, 1, 1]}>
                <mesh geometry={nodes.Tube002_adaptor_0.geometry} material={nodes.Tube002_adaptor_0.material} />
              </group>
              <group
                position={[-75.22, 1814.17, 52.56]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line036_01_-_Default_0'].geometry}
                    material={nodes['Line036_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[353.09, 1814.46, 52.56]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line037_01_-_Default_0'].geometry}
                    material={nodes['Line037_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[137.73, 780.13, -5.05]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.97, 0.99, 1.22]}>
                <mesh geometry={nodes.Box021_dfhg_0.geometry} material={nodes.Box021_dfhg_0.material} />
              </group>
              <group position={[-58.32, 1899.06, 1.11]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.43, 0.43, 0.43]}>
                <mesh
                  geometry={nodes['Bwalle_004_Material_#33_0'].geometry}
                  material={nodes['Bwalle_004_Material_#33_0'].material}
                />
              </group>
              <group position={[-45.07, 1869.51, -38.15]} scale={0.13}>
                <mesh
                  geometry={nodes['Cylinder014_Material_#32_0'].geometry}
                  material={nodes['Cylinder014_Material_#32_0'].material}
                />
              </group>
              <group position={[-324.07, -43.05, -37.16]}>
                <mesh geometry={nodes['Box022_02_-_Defaultmo_0'].geometry} material={materials['02_-_Defaultmo']} />
              </group>
              <group position={[-286.99, 207.77, -9.57]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Cylinder010_adaptor_0.geometry} material={nodes.Cylinder010_adaptor_0.material} />
              </group>
              <group position={[-362.33, 207.77, -9.57]} rotation={[Math.PI / 2, 0, 0]} scale={[-1, 1, 1]}>
                <mesh geometry={nodes.Cylinder011_adaptor_0.geometry} material={nodes.Cylinder011_adaptor_0.material} />
              </group>
              <group position={[114.91, -479.92, -30.57]} scale={0.26}>
                <group position={[55.75, -16.32, 0]}>
                  <mesh
                    geometry={nodes['ChamferBox003_Material_#31_0'].geometry}
                    material={nodes['ChamferBox003_Material_#31_0'].material}
                  />
                </group>
              </group>
              <group position={[337.34, -1949.54, -37.63]} rotation={[0, 0, Math.PI]} scale={[0.26, 0.26, 0.26]}>
                <group position={[55.75, -16.32, 0]}>
                  <mesh
                    geometry={nodes['ChamferBox004_Material_#31_0'].geometry}
                    material={nodes['ChamferBox004_Material_#31_0'].material}
                  />
                </group>
              </group>
              <group position={[-81.21, -1927.68, -38.52]} rotation={[0, 0, -Math.PI]} scale={[0.23, 0.21, 0.26]}>
                <mesh
                  geometry={nodes['Cylinder012_Material_#32_0'].geometry}
                  material={nodes['Cylinder012_Material_#32_0'].material}
                />
              </group>
              <group
                position={[-99.26, -1728.16, -29.74]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[-0.23, 0.23, 0.23]}>
                <mesh
                  geometry={nodes['ChamferBox005_Material_#30_0'].geometry}
                  material={nodes['ChamferBox005_Material_#30_0'].material}
                />
              </group>
              <group
                position={[-99.26, -1767.66, -29.74]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[-0.23, 0.23, 0.23]}>
                <mesh
                  geometry={nodes['ChamferBox006_Material_#30_0'].geometry}
                  material={nodes['ChamferBox006_Material_#30_0'].material}
                />
              </group>
              <group
                position={[-99.26, -1688.7, -29.74]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[-0.23, 0.23, 0.23]}>
                <mesh
                  geometry={nodes['ChamferBox007_Material_#30_0'].geometry}
                  material={nodes['ChamferBox007_Material_#30_0'].material}
                />
              </group>
              <group
                position={[-99.26, -1728.16, -13.91]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[-0.23, 0.23, 0.23]}>
                <mesh
                  geometry={nodes['ChamferBox008_Material_#30_0'].geometry}
                  material={nodes['ChamferBox008_Material_#30_0'].material}
                />
              </group>
              <group position={[297.97, -1766.19, -14.75]} rotation={[0, 0, -Math.PI / 2]} scale={[0.42, 0.46, 0.46]}>
                <mesh
                  geometry={nodes['Box023_Material_#28_0'].geometry}
                  material={nodes['Box023_Material_#28_0'].material}
                />
              </group>
              <group position={[297.97, -1676.96, -14.75]} rotation={[0, 0, -Math.PI / 2]} scale={[0.42, 0.46, 0.46]}>
                <mesh
                  geometry={nodes['Box024_Material_#28_0'].geometry}
                  material={nodes['Box024_Material_#28_0'].material}
                />
              </group>
              <group
                position={[328.22, -1529.1, -19.77]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.46, 0.18, 1.3]}>
                <mesh
                  geometry={nodes['sangar_005_Material_#27_0'].geometry}
                  material={nodes['sangar_005_Material_#27_0'].material}
                />
              </group>
              <group
                position={[98.61, -1262.45, -19.77]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.46, 0.18, 1.3]}>
                <mesh
                  geometry={nodes['sangar_006_Material_#27_0'].geometry}
                  material={nodes['sangar_006_Material_#27_0'].material}
                />
              </group>
              <group
                position={[123.14, -862.06, -21.49]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[-0.19, 0.27, 0.36]}>
                <mesh
                  geometry={nodes.ChamferBox009_sdsdsds_0.geometry}
                  material={nodes.ChamferBox009_sdsdsds_0.material}
                />
              </group>
              <group
                position={[-107.6, -526.66, -21.83]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.46, 0.18, 1.3]}>
                <mesh
                  geometry={nodes['sangar_007_Material_#27_0'].geometry}
                  material={nodes['sangar_007_Material_#27_0'].material}
                />
              </group>
              <group
                position={[-355.48, -498.23, -15.15]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[-0.46, 0.46, 0.46]}>
                <mesh
                  geometry={nodes['ChamferBox010_Material_#30_0'].geometry}
                  material={nodes['ChamferBox010_Material_#30_0'].material}
                />
              </group>
              <group
                position={[-168.45, 447.16, -21.16]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={[-0.31, 0.31, 0.31]}>
                <mesh
                  geometry={nodes['ChamferBox011_Material_#30_0'].geometry}
                  material={nodes['ChamferBox011_Material_#30_0'].material}
                />
              </group>
              <group
                position={[152.65, 799.55, -16.74]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.27, 0.11, 0.76]}>
                <mesh
                  geometry={nodes['sangar_008_Material_#27_0'].geometry}
                  material={nodes['sangar_008_Material_#27_0'].material}
                />
              </group>
              <group
                position={[177.57, 1298.09, -27.57]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[-0.19, 0.27, 0.36]}>
                <mesh
                  geometry={nodes.ChamferBox012_sdsdsds_0.geometry}
                  material={nodes.ChamferBox012_sdsdsds_0.material}
                />
              </group>
              <group position={[136.74, 1511.95, -20.69]} rotation={[Math.PI / 2, 0, 0]} scale={[0.46, 0.18, 1.3]}>
                <mesh
                  geometry={nodes['sangar_009_Material_#27_0'].geometry}
                  material={nodes['sangar_009_Material_#27_0'].material}
                />
              </group>
              <group position={[358.58, 1892.33, -38.67]} scale={[0.22, 0.22, 0.25]}>
                <mesh
                  geometry={nodes['Cylinder013_Material_#32_0'].geometry}
                  material={nodes['Cylinder013_Material_#32_0'].material}
                />
              </group>
              <group position={[337.41, 1885.7, 5.53]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  geometry={nodes['Sphere001_03_-_Defaultxcv_0'].geometry}
                  material={materials['03_-_Defaultxcv']}
                />
              </group>
              <group position={[-323.27, 221.08, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 4]}>
                <mesh geometry={nodes.Tube003_adaptor_0.geometry} material={nodes.Tube003_adaptor_0.material} />
              </group>
              <group position={[-323.27, -258.3, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 4]}>
                <mesh geometry={nodes.Tube004_adaptor_0.geometry} material={nodes.Tube004_adaptor_0.material} />
              </group>
              <group position={[-320.89, 199.22, 57.45]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object022_02_-_Default_0'].geometry}
                    material={nodes['Object022_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-233.22, 199.22, 3.75]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object023_02_-_Default_0'].geometry}
                    material={nodes['Object023_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-323.03, 199.22, 57.45]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object025_02_-_Default_0'].geometry}
                    material={nodes['Object025_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-301.99, 199.22, 66.1]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object026_02_-_Default_0'].geometry}
                    material={nodes['Object026_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-265.6, 199.22, 66.1]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object027_02_-_Default_0'].geometry}
                    material={nodes['Object027_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-246.59, 199.22, 57.45]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object028_02_-_Default_0'].geometry}
                    material={nodes['Object028_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[298.96, -1814.07, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object064_02_-_Default_0'].geometry}
                    material={nodes['Object064_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[386.63, -1814.07, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object065_02_-_Default_0'].geometry}
                    material={nodes['Object065_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[285.46, -1814.07, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object066_02_-_Default_0'].geometry}
                    material={nodes['Object066_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[296.82, -1814.07, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object067_02_-_Default_0'].geometry}
                    material={nodes['Object067_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[317.86, -1814.07, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object068_02_-_Default_0'].geometry}
                    material={nodes['Object068_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[354.25, -1814.07, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object069_02_-_Default_0'].geometry}
                    material={nodes['Object069_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[373.26, -1814.07, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object070_02_-_Default_0'].geometry}
                    material={nodes['Object070_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[298.96, -1655.47, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object078_02_-_Default_0'].geometry}
                    material={nodes['Object078_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[386.63, -1655.47, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object079_02_-_Default_0'].geometry}
                    material={nodes['Object079_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[285.46, -1655.47, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object080_02_-_Default_0'].geometry}
                    material={nodes['Object080_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[296.82, -1655.47, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object081_02_-_Default_0'].geometry}
                    material={nodes['Object081_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[317.86, -1655.47, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object082_02_-_Default_0'].geometry}
                    material={nodes['Object082_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[354.25, -1655.47, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object083_02_-_Default_0'].geometry}
                    material={nodes['Object083_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[373.26, -1655.47, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object084_02_-_Default_0'].geometry}
                    material={nodes['Object084_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[352.76, -1568.84, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line022_01_-_Default_0'].geometry}
                    material={nodes['Line022_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-21.09, -1813.79, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object092_02_-_Default_0'].geometry}
                    material={nodes['Object092_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-108.76, -1813.79, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object093_02_-_Default_0'].geometry}
                    material={nodes['Object093_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-7.59, -1813.79, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object094_02_-_Default_0'].geometry}
                    material={nodes['Object094_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-18.95, -1813.79, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object095_02_-_Default_0'].geometry}
                    material={nodes['Object095_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-39.99, -1813.79, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object096_02_-_Default_0'].geometry}
                    material={nodes['Object096_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-76.38, -1813.79, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object097_02_-_Default_0'].geometry}
                    material={nodes['Object097_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-95.39, -1813.79, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object098_02_-_Default_0'].geometry}
                    material={nodes['Object098_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-21.09, -1655.19, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object099_02_-_Default_0'].geometry}
                    material={nodes['Object099_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-108.76, -1655.19, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object100_02_-_Default_0'].geometry}
                    material={nodes['Object100_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-7.59, -1655.19, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object101_02_-_Default_0'].geometry}
                    material={nodes['Object101_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-18.95, -1655.19, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object102_02_-_Default_0'].geometry}
                    material={nodes['Object102_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-39.99, -1655.19, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object103_02_-_Default_0'].geometry}
                    material={nodes['Object103_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-76.38, -1655.19, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object104_02_-_Default_0'].geometry}
                    material={nodes['Object104_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-95.39, -1655.19, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object105_02_-_Default_0'].geometry}
                    material={nodes['Object105_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-74.89, -1568.56, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line025_01_-_Default_0'].geometry}
                    material={nodes['Line025_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[154.01, -1536.43, 52.56]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line026_01_-_Default_0'].geometry}
                    material={nodes['Line026_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[99.84, -1298.35, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object120_02_-_Default_0'].geometry}
                    material={nodes['Object120_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[187.51, -1298.35, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object121_02_-_Default_0'].geometry}
                    material={nodes['Object121_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[86.34, -1298.35, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object122_02_-_Default_0'].geometry}
                    material={nodes['Object122_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[97.69, -1298.35, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object123_02_-_Default_0'].geometry}
                    material={nodes['Object123_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[118.74, -1298.35, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object124_02_-_Default_0'].geometry}
                    material={nodes['Object124_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[155.13, -1298.35, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object125_02_-_Default_0'].geometry}
                    material={nodes['Object125_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[174.14, -1298.35, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object126_02_-_Default_0'].geometry}
                    material={nodes['Object126_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[99.84, -1139.75, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object127_02_-_Default_0'].geometry}
                    material={nodes['Object127_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[187.51, -1139.75, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object128_02_-_Default_0'].geometry}
                    material={nodes['Object128_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[86.34, -1139.75, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object129_02_-_Default_0'].geometry}
                    material={nodes['Object129_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[97.69, -1139.75, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object130_02_-_Default_0'].geometry}
                    material={nodes['Object130_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[118.74, -1139.75, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object131_02_-_Default_0'].geometry}
                    material={nodes['Object131_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[155.13, -1139.75, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object132_02_-_Default_0'].geometry}
                    material={nodes['Object132_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[174.14, -1139.75, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object133_02_-_Default_0'].geometry}
                    material={nodes['Object133_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[174.14, 1068.08, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object134_02_-_Default_0'].geometry}
                    material={nodes['Object134_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[155.13, 1068.08, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object135_02_-_Default_0'].geometry}
                    material={nodes['Object135_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[118.74, 1068.08, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object136_02_-_Default_0'].geometry}
                    material={nodes['Object136_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[97.69, 1068.08, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object137_02_-_Default_0'].geometry}
                    material={nodes['Object137_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[86.34, 1068.08, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object138_02_-_Default_0'].geometry}
                    material={nodes['Object138_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[187.51, 1068.08, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object139_02_-_Default_0'].geometry}
                    material={nodes['Object139_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[99.84, 1068.08, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object140_02_-_Default_0'].geometry}
                    material={nodes['Object140_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[298.96, 1583.8, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object141_02_-_Default_0'].geometry}
                    material={nodes['Object141_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[386.63, 1583.8, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object142_02_-_Default_0'].geometry}
                    material={nodes['Object142_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[285.46, 1583.8, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object143_02_-_Default_0'].geometry}
                    material={nodes['Object143_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[296.82, 1583.8, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object144_02_-_Default_0'].geometry}
                    material={nodes['Object144_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[317.86, 1583.8, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object145_02_-_Default_0'].geometry}
                    material={nodes['Object145_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[354.25, 1583.8, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object146_02_-_Default_0'].geometry}
                    material={nodes['Object146_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[373.26, 1583.8, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object147_02_-_Default_0'].geometry}
                    material={nodes['Object147_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[352.76, 1497.17, 52.56]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line030_01_-_Default_0'].geometry}
                    material={nodes['Line030_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[174.14, 1226.68, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object155_02_-_Default_0'].geometry}
                    material={nodes['Object155_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[155.13, 1226.68, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object156_02_-_Default_0'].geometry}
                    material={nodes['Object156_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[118.74, 1226.68, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object157_02_-_Default_0'].geometry}
                    material={nodes['Object157_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[97.69, 1226.68, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object158_02_-_Default_0'].geometry}
                    material={nodes['Object158_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[86.34, 1226.68, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object159_02_-_Default_0'].geometry}
                    material={nodes['Object159_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[187.51, 1226.68, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object160_02_-_Default_0'].geometry}
                    material={nodes['Object160_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[99.84, 1226.68, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object161_02_-_Default_0'].geometry}
                    material={nodes['Object161_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-21.09, 1583.52, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object162_02_-_Default_0'].geometry}
                    material={nodes['Object162_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-108.76, 1583.52, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object163_02_-_Default_0'].geometry}
                    material={nodes['Object163_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-7.59, 1583.52, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object164_02_-_Default_0'].geometry}
                    material={nodes['Object164_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-18.95, 1583.52, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object165_02_-_Default_0'].geometry}
                    material={nodes['Object165_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-39.99, 1583.52, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object166_02_-_Default_0'].geometry}
                    material={nodes['Object166_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-76.38, 1583.52, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object167_02_-_Default_0'].geometry}
                    material={nodes['Object167_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-95.39, 1583.52, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object168_02_-_Default_0'].geometry}
                    material={nodes['Object168_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-74.89, 1496.89, 52.56]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line032_01_-_Default_0'].geometry}
                    material={nodes['Line032_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[154.01, 1464.76, 52.56]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, -2.87]}>
                  <mesh
                    geometry={nodes['Line033_01_-_Default_0'].geometry}
                    material={nodes['Line033_01_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-76.38, 1742.12, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object183_02_-_Default_0'].geometry}
                    material={nodes['Object183_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-39.99, 1742.12, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object184_02_-_Default_0'].geometry}
                    material={nodes['Object184_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-18.95, 1742.12, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object185_02_-_Default_0'].geometry}
                    material={nodes['Object185_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-7.59, 1742.12, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object186_02_-_Default_0'].geometry}
                    material={nodes['Object186_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-108.76, 1742.12, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object187_02_-_Default_0'].geometry}
                    material={nodes['Object187_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-21.09, 1742.12, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object188_02_-_Default_0'].geometry}
                    material={nodes['Object188_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-95.39, 1742.12, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object196_02_-_Default_0'].geometry}
                    material={nodes['Object196_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[373.26, 1742.4, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object189_02_-_Default_0'].geometry}
                    material={nodes['Object189_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[354.25, 1742.4, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object190_02_-_Default_0'].geometry}
                    material={nodes['Object190_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[317.86, 1742.4, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object191_02_-_Default_0'].geometry}
                    material={nodes['Object191_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[296.82, 1742.4, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object192_02_-_Default_0'].geometry}
                    material={nodes['Object192_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[285.46, 1742.4, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object193_02_-_Default_0'].geometry}
                    material={nodes['Object193_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[386.63, 1742.4, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object194_02_-_Default_0'].geometry}
                    material={nodes['Object194_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[298.96, 1742.4, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object195_02_-_Default_0'].geometry}
                    material={nodes['Object195_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[298.64, -1496.79, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object085_02_-_Default_0'].geometry}
                    material={nodes['Object085_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[386.31, -1496.79, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object086_02_-_Default_0'].geometry}
                    material={nodes['Object086_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[285.13, -1496.79, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object087_02_-_Default_0'].geometry}
                    material={nodes['Object087_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[296.49, -1496.79, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object088_02_-_Default_0'].geometry}
                    material={nodes['Object088_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[317.54, -1496.79, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object089_02_-_Default_0'].geometry}
                    material={nodes['Object089_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[353.92, -1496.79, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object090_02_-_Default_0'].geometry}
                    material={nodes['Object090_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[372.93, -1496.79, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object091_02_-_Default_0'].geometry}
                    material={nodes['Object091_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-20.77, -1496.5, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object106_02_-_Default_0'].geometry}
                    material={nodes['Object106_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-108.44, -1496.5, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object107_02_-_Default_0'].geometry}
                    material={nodes['Object107_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-7.26, -1496.5, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object108_02_-_Default_0'].geometry}
                    material={nodes['Object108_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-18.62, -1496.5, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object109_02_-_Default_0'].geometry}
                    material={nodes['Object109_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-39.67, -1496.5, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object110_02_-_Default_0'].geometry}
                    material={nodes['Object110_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-76.05, -1496.5, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object111_02_-_Default_0'].geometry}
                    material={nodes['Object111_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[-95.06, -1496.5, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object112_02_-_Default_0'].geometry}
                    material={nodes['Object112_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[99.89, -1608.48, 24.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object113_02_-_Default_0'].geometry}
                    material={nodes['Object113_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[187.56, -1608.48, -29.16]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object114_02_-_Default_0'].geometry}
                    material={nodes['Object114_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[86.39, -1608.48, -29.16]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object115_02_-_Default_0'].geometry}
                    material={nodes['Object115_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[97.74, -1608.48, 24.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object116_02_-_Default_0'].geometry}
                    material={nodes['Object116_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[118.79, -1608.48, 33.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object117_02_-_Default_0'].geometry}
                    material={nodes['Object117_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[155.18, -1608.48, 33.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object118_02_-_Default_0'].geometry}
                    material={nodes['Object118_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[174.18, -1608.48, 24.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object119_02_-_Default_0'].geometry}
                    material={nodes['Object119_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[298.64, 1425.12, 24.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object148_02_-_Default_0'].geometry}
                    material={nodes['Object148_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[386.31, 1425.12, -29.16]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object149_02_-_Default_0'].geometry}
                    material={nodes['Object149_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[285.13, 1425.12, -29.16]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object150_02_-_Default_0'].geometry}
                    material={nodes['Object150_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[296.49, 1425.12, 24.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object151_02_-_Default_0'].geometry}
                    material={nodes['Object151_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[317.54, 1425.12, 33.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object152_02_-_Default_0'].geometry}
                    material={nodes['Object152_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[353.92, 1425.12, 33.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object153_02_-_Default_0'].geometry}
                    material={nodes['Object153_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[372.93, 1425.12, 24.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={25.1}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object154_02_-_Default_0'].geometry}
                    material={nodes['Object154_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-20.77, 1424.83, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object169_02_-_Default_0'].geometry}
                    material={nodes['Object169_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-108.44, 1424.83, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object170_02_-_Default_0'].geometry}
                    material={nodes['Object170_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-7.26, 1424.83, -29.16]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object171_02_-_Default_0'].geometry}
                    material={nodes['Object171_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-18.62, 1424.83, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object172_02_-_Default_0'].geometry}
                    material={nodes['Object172_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-39.67, 1424.83, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object173_02_-_Default_0'].geometry}
                    material={nodes['Object173_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-76.05, 1424.83, 33.19]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object174_02_-_Default_0'].geometry}
                    material={nodes['Object174_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group
                position={[-95.06, 1424.83, 24.53]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object175_02_-_Default_0'].geometry}
                    material={nodes['Object175_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[99.89, 1536.81, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object176_02_-_Default_0'].geometry}
                    material={nodes['Object176_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[187.56, 1536.81, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object177_02_-_Default_0'].geometry}
                    material={nodes['Object177_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[86.39, 1536.81, -29.16]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object178_02_-_Default_0'].geometry}
                    material={nodes['Object178_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[97.74, 1536.81, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object179_02_-_Default_0'].geometry}
                    material={nodes['Object179_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[118.79, 1536.81, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object180_02_-_Default_0'].geometry}
                    material={nodes['Object180_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[155.18, 1536.81, 33.19]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object181_02_-_Default_0'].geometry}
                    material={nodes['Object181_02_-_Default_0'].material}
                  />
                </group>
              </group>
              <group position={[174.18, 1536.81, 24.53]} rotation={[Math.PI / 2, 0, 0]} scale={[-25.1, 25.1, 25.1]}>
                <group position={[-0.5, -1.96, 0]}>
                  <mesh
                    geometry={nodes['Object182_02_-_Default_0'].geometry}
                    material={nodes['Object182_02_-_Default_0'].material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/level/scene.gltf')
