/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: olofunot (https://sketchfab.com/olofunot)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/b4b5931851754747a734f72234c87e38
title: Industrial robot arm
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/model/scene.gltf", "/model/scene.bin")
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    actions["Take 001"].play();
    console.log(actions)
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.18, 72.55, 33.45]} rotation={[-1.31, -1.57, 0]}>
            <group position={[0.2, 0.17, 1.18]} scale={[1, 0.86, 1]}>
              <group position={[0.85, 96.65, -2.55]} rotation={[0, 0, -1.5]} scale={[1.1, 0.95, 0.95]}>
                <group
                  position={[-0.3, 0.23, -2.23]}
                  rotation={[-Math.PI / 2, -0.17, Math.PI / 2]}
                  scale={[1.06, 1.06, 1.06]}>
                  <group position={[0, -35.67, 6.01]} rotation={[0.17, 0, 0]}>
                    <group position={[0.02, -5.17, -1.49]} rotation={[-0.17, 0, 0]}>
                      <group position={[-0.06, -12.53, -0.94]} rotation={[0.17, 0, 0]} scale={[0.26, 0.21, 0.5]}>
                        <group position={[0.12, -56.61, 0]}>
                          <mesh
                            geometry={nodes['Rectangle001_Material_#13_0'].geometry}
                            material={materials.Material_13}
                          />
                        </group>
                        <group
                          position={[-8.5, -62.38, 6.55]}
                          rotation={[-1.57, -Math.PI / 2, 0]}
                          scale={[5.93, 2.08, 7.4]}>
                          <group
                            position={[0, 0, -0.06]}
                            rotation={[Math.PI / 2, 0.9, -1.57]}
                            scale={[0.53, 0.8, 0.97]}>
                            <mesh
                              geometry={nodes['Line013_Material_#14_0'].geometry}
                              material={materials.Material_14}
                            />
                          </group>
                          <group position={[0, 6.39, -0.06]} scale={[1, 1, 1.28]}>
                            <group position={[-5.37, 0.13, 0]}>
                              <mesh
                                geometry={nodes['Line012_Material_#17_0'].geometry}
                                material={materials.Material_17}
                              />
                            </group>
                          </group>
                          <mesh
                            geometry={nodes['Circle011_Material_#19_0'].geometry}
                            material={materials.Material_19}
                          />
                        </group>
                      </group>
                      <mesh geometry={nodes['Circle009_Material_#12_0'].geometry} material={materials.Material_12} />
                    </group>
                    <group rotation={[-0.17, 0, 0]}>
                      <mesh geometry={nodes['Object002_Material_#11_0'].geometry} material={materials.Material_11} />
                    </group>
                  </group>
                  <group position={[0, -35.78, 5.99]}>
                    <mesh geometry={nodes['Circle006_Material_#10_0'].geometry} material={materials.Material_10} />
                  </group>
                  <group position={[4.02, -2.89, 16.7]} rotation={[1.75, Math.PI / 2, 0]}>
                    <mesh geometry={nodes['Line010_Material_#22_0'].geometry} material={materials.Material_22} />
                  </group>
                </group>
                <group position={[0, 0, -4.46]}>
                  <mesh geometry={nodes['Cylinder004_Material_#9_0'].geometry} material={materials.Material_9} />
                </group>
                <group position={[-0.09, 0.36, 4.02]} scale={[0.52, 0.52, 0.5]}>
                  <group position={[16.75, 0, 0]}>
                    <mesh geometry={nodes['NGon005_Material_#15_0'].geometry} material={materials.Material_15} />
                  </group>
                </group>
              </group>
              <group position={[0.53, 51.18, 0]}>
                <mesh geometry={nodes['Box001_Material_#8_0'].geometry} material={materials.Material_8} />
              </group>
            </group>
            <group position={[-0.78, 40.74, 8.24]} rotation={[0, 1.57, 0]} scale={[1, 0.86, 1]}>
              <group position={[1.31, 84.68, -130.03]} rotation={[-0.07, 0, 0]} scale={[1, 1.17, 1]}>
                <mesh geometry={nodes['Object001_Material_#20_0'].geometry} material={materials.Material_20} />
              </group>
              <mesh geometry={nodes['Line004_Material_#18_0'].geometry} material={materials.Material_18} />
            </group>
            <mesh geometry={nodes['Cylinder003_Material_#7_0'].geometry} material={materials.Material_7} />
          </group>
          <group name="Line020" position={[4.42, 1.59, 60.38]} rotation={[-0.79, -1.56, Math.PI / 4]} scale={0.34}>
            <group position={[27.43, -2.81, 0]}>
              <mesh geometry={nodes['Line020_��l2_0'].geometry} material={materials.material} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cylinder002_bott_0.geometry} material={materials.bott} />
          </group>
          <group position={[12.09, 72.54, 34.07]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Circle001_Material_#6_0'].geometry} material={materials.Material_6} />
          </group>
          <group position={[1.64, 61.87, 0.78]}>
            <mesh geometry={nodes['Line002_Material_#21_0'].geometry} material={materials.Material_21} />
          </group>
          <group position={[28.42, 1.89, -33.76]} rotation={[-Math.PI / 2, 0, 0]} scale={0.65}>
            <mesh geometry={nodes['NGon003_Material_#24_0'].geometry} material={materials.Material_24} />
          </group>
          <group position={[-1.86, 0, 57.9]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Rectangle002_back_0.geometry} material={materials.back} />
          </group>
          <group position={[-1.43, 11, 60.38]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.34}>
            <group position={[0, -2.81, 0]}>
              <mesh geometry={nodes['Line024_��l_0'].geometry} material={materials.material_21} />
            </group>
          </group>
          <group position={[-5.75, 26.72, -7.2]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Circle002_Material_#23_0'].geometry} material={materials.Material_23} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/scene.gltf')
